# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozt97qSog6DpS4VG3hI7PnvSFO1s9rJa
"""

import streamlit as st

# ---------------------------
# Portfolio Web App
# ---------------------------

# Page config
st.set_page_config(page_title="Menna Elgabry | Portfolio", page_icon="🤖", layout="wide")

# Centered header with image
col1, col2, col3 = st.columns([1,2,1])  # create empty columns to center
with col2:
    st.image("/content/my_pic.jpg", width=250)  # your uploaded picture
    st.title("👩‍💻 Menna Elgabry")
    st.subheader("Machine Learning Engineer | AI Researcher")
    st.write("📧", "[Email](mailto:mennayasser891@gmail.com) | 🌐 [LinkedIn](https://www.linkedin.com/in/menna-yasser-0029221b4/)")

st.markdown("---")

# Vision / About
st.markdown("### 🌟 About Me")
st.write("""
I help researchers, startups, and businesses turn raw data into intelligent solutions that save time,
uncover insights, and support better decisions. With expertise across supervised and unsupervised learning,
computer vision, and large language models, I design AI systems that tackle real challenges like fraud detection,
customer feedback analysis, trend prediction, image-based diagnosis, and automated reporting.
""")

# Education
st.markdown("### 🎓 Education")
st.write("- **BSc Computer Science, MSA University** (2022 - 2026)")
st.write("- **BSc Computer Science, Greenwich University** (2022 - 2026)")

# Work Experience
st.markdown("### 💼 Work Experience")
st.write("- **Machine Learning Intern** – Hands-on AI development pipeline (ML + DL).")
st.write("- **Digital Egyptian Pioneers Intern** – Digital transformation, data literacy, analytics.")
st.write("- **CIB Summer Intern** – Applied data solutions to banking and financial scenarios.")

# Services
st.markdown("### 🛠️ Services")
st.write("""
- AI-powered business predictions
- Customer & market insights (NLP, sentiment, fraud detection)
- Intelligent image analysis (medical imaging, defect detection, sign language support)
""")

# Professional Projects
st.markdown("### 📂 Projects")
st.write("- **Sign Language Recognition** (EfficientNet) – Selected for MSA Deep Minds 5 🎉")
st.write("- **Student & Staff Feedback Monitoring System** – Selected for MSA Deep Minds 3 🏆")
st.write("- **Image Segmentation (U-Net + Attention)**")
st.write("- **Emotion Detection Bot using LLMs**")
st.write("- **Mini Games Development** (C++, C#, .NET, Visual Studio)")

# Research
st.markdown("### 📑 Research")
st.write("""
**Optimizing Sign Language Detection with Deep Learning and Preprocessing: A Comparative Study of CNN-Based Models**
- Accepted at ICEEM-IEEE 2025
- Benchmarked preprocessing methods (grayscale, CLAHE, gamma correction, contrast stretching).
- Identified EfficientNet as best model for ASL recognition.
""")

# Skills
st.markdown("### 🧠 Technical Skills")
st.write("""
- Machine Learning: Supervised, Unsupervised, CNN, ResNet, LSTM, Autoencoders, GANs, LLMs
- Data Structures & Algorithms
- Web Development: HTML, CSS, JS, PHP, WAMP, XAMPP
- Databases: MySQL, MongoDB
- OOP, OOSE
""")

st.markdown("### 🤝 Personal Skills")
st.write("Communication | Adaptability | Teamwork")

# Certifications
st.markdown("### 📜 Certifications")
st.write("""
- Generative AI (Transformers) – IBM + Coursera (Ongoing)
- Deep Learning – Neurotech (June 2024)
- Machine Learning – DEPI (2025)
- CIB Summer Internship Program (2024)
- Ethical Hacking – EC-Council (July 2023)
- Introduction to MongoDB – Mahara-Tech (2023)
""")

# Footer
st.markdown("---")
st.write("💡 If you want to save time and money, let's work together!")